### ISSUE TITLE
Time error in creating basic ingest

### ISSUE THREAD

**Issue by syedhamidali** [ARM-DOE/pyart#1011]
Dear Pyart Team,
I was trying to create basic ingest, but it is encountering some errors in time. Can you please have a look?
I have separate data files for each scan (total 10 sweeps), and I wanted to create pyart compatible file, having all scans in one.
You can download the data file here [archive.zip](https://drive.google.com/file/d/1jONSBlfhTPHRCFyEFKertzp7LYO7fzjr/view?usp=sharing)

**Comment by zssherman** [comment]
Hi @syedhamidali

I couldn't reproduce the time error, however the error i did run into was in the cfradial write the sweep number is failing. The radar.nsweeps doesn't match the radar.sweep_numbers. To fix this I did this before the writer:

radar.nsweeps = 10

Also I saw the radar.gate_latitude['data'] etc lines were failing, this is due to the radar.latitude['data'] etc not being set with np.array, to fix this:

radar.latitude['data'] = np.array([ds.siteLat.values])
radar.longitude['data'] = np.array([ds.siteLon.values])
radar.altitude['data'] = np.array([ds.siteAlt.values])

I was then able to run and write the file out with no errors.

**Comment by syedhamidali** [comment]
Dear @zssherman, Thank you.
Was it the right approach to compile the data into one?
Please let me know so that I could close this issue.

**Comment by syedhamidali** [comment]
I also tried reading data with netCDF4, it fits data properly, but the time there is again wrong, as you can see in the figures.
![image](https://user-images.githubusercontent.com/35923822/133094564-826e6b45-ecc0-4192-8be6-32331de90e40.png)

![image](https://user-images.githubusercontent.com/35923822/133094861-64a8605a-db20-4433-b046-a8095cdf7362.png)

![image](https://user-images.githubusercontent.com/35923822/133095023-8ca1bada-7838-4160-a96b-81d77c4e59a9.png)

**Comment by kmuehlbauer** [comment]
@syedhamidali looks like you would need to use Linux timestamp seconds since 01.01.1970 :-)

**Comment by syedhamidali** [comment]
Thanks, @kmuehlbauer - It solved the problem.
