### ISSUE TITLE
Possible issue with region based dealiasing 

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/pyart#1340]
When I was going through and adding pre-commit hooks, I noticed the following issue in the region based dealiasing module

The `vel_wo_cur` variable is never used...

https://github.com/ARM-DOE/pyart/blob/main/pyart/correct/region_dealias.py#L463

Should we be setting that value to some array? Do we need to store it somewhere? It was changed by @rcjackson last year I think

**Comment by mgrover1** [comment]
Here is the commit that changed the behavior here 
https://github.com/ARM-DOE/pyart/commit/7485d867cbf4d726b11c3bc95206da74bd4084f4

**Comment by rcjackson** [comment]
It’s not used anymore but left over there on accident. The references can be removed since they are not used.

Bobby

From: Max Grover ***@***.***>
Date: Monday, December 5, 2022 at 12:22 PM
To: ARM-DOE/pyart ***@***.***>
Cc: Jackson, Robert ***@***.***>, Mention ***@***.***>
Subject: [ARM-DOE/pyart] Possible issue with region based dealiasing (Issue #1340)

When I was going through and adding pre-commit hooks, I noticed the following issue in the region based dealiasing module

The vel_wo_cur variable is never used...

https://github.com/ARM-DOE/pyart/blob/main/pyart/correct/region_dealias.py#L463

Should we be setting that value to some array? Do we need to store it somewhere? It was changed by @rcjackson<https://github.com/rcjackson> last year I think
