### ISSUE TITLE
Replace the xdrlib package in NEXRAD Level3 reader

### ISSUE THREAD

**Issue by mgrover1** [ARM-DOE/pyart#1344]
As mentioned by @jrobrien91 , The `xdrlib` module is slated for removal in Python 3.13, so we should replace the use of that module in the NEXRAD Level3 reader.

```bash
DeprecationWarning: 'xdrlib' is deprecated and slated for removal in Python 3.13
 from xdrlib import Unpacker
```

**Comment by zssherman** [comment]
@mgrover1 I'm wondering if we can directly implement the code found here:
https://github.com/python/cpython/blob/main/Lib/xdrlib.py#L135

**Comment by zssherman** [comment]
Can add the class to nexrad_common.py and import from there possibly?

**Comment by mgrover1** [comment]
We could - I would like to investigate why they are deprecating this first to see if we would be taking on quite a bit of technical debt

**Comment by zssherman** [comment]
Yeah, sound likes a plan. From what I read, it was mostly an older format for the 1980s that doesn't look to be used anymore. But i'm assuming, there are still nexrad 3 files that follow this, which could be an issue.

**Comment by dopplershift** [comment]
Python removed it because they were removing "unused batteries" and this was one of them. It does seem like an odd thing to have in the standard library given that it doesn't really seem used (outside of NEXRD level 3 😆 )  We're looking at this in Unidata/MetPy#2818.

Right now based on [Python's code](https://github.com/python/cpython/blob/024ac542d738f56b36bdeb3517a10e93da5acab9/Lib/xdrlib.py) at worst I'd probably vendor the stdlib `Unpacker` class, but I'm also tempted to just re-implement the few fields we need using our existing binary I/O support--the format doesn't actually look all that magical.

**Comment by zssherman** [comment]
@dopplershift Ah gotcha makes sense, thanks for the clarification!

**Comment by kmuehlbauer** [comment]
JFTR, others seem to have extracted xdrlib from the python codebase, see https://github.com/MDAnalysis/mda-xdrlib. This is also available as standalone package from conda-forge, https://github.com/conda-forge/mda-xdrlib-feedstock.

**Comment by mgrover1** [comment]
Thanks @kmuehlbauer !! This should be as easy as adding that as a dependency?

**Comment by dopplershift** [comment]
Just FYI, if you ever wanted to avoid the dependency, MetPy only need to add about [30 lines](https://github.com/Unidata/MetPy/pull/3117/files) to cover what was needed
