### ISSUE TITLE
UF File Writing

### ISSUE THREAD

**Issue by josephhardinee** [ARM-DOE/pyart#186]
This is mostly as a placeholder to reduce duplicated work. 
Py-Art needs the ability to write UF files. I have most of a PR ready that implements this, just gotta iron out a few things and ensure RSL compatibility.

**Comment by jjhelmus** [comment]
@josephhardinee Any updates on this work?

**Comment by josephhardinee** [comment]
It kind of got strangled by dissertation writing. Hopefully I should be able to revisit it very soon.

**Comment by gamaanderson** [comment]
Is some one working in this issue? Responding from a request from Simepar, I would like to get to it.

**Comment by jjhelmus** [comment]
@josephhardinee mentioned he had some code for this at the AMS radar meeting.  

Since I added support for reading UF and am now well versed in the format I can try to code something up this afternoon.

**Comment by jjhelmus** [comment]
In progress work on a UF writing appears in the [jjhelmus/pyart/uf_write](https://github.com/jjhelmus/pyart/tree/uf_writer) branch.  This branch will rebased when complete.

**Comment by jjhelmus** [comment]
Closed with the merging of #388

**Comment by gamaanderson** [comment]
Nice work @jjhelmus

@TulipaSilva can you please confirm that TITAN is recognizing this UF-files. If you don't have the time, ask someone else, Beneti is aware of that.

**Comment by jjhelmus** [comment]
Let me know if there are any issue with UF writing that you find.  Code coverage is 100% but it could still use some testing with real world files.  Two other things to keep in mind are:

* Py-ART is writing UF files with 2-byte padding around each record, this is consistent with the files RSL creates but may not be supported by all software.  If you need 1-byte or no padding files open an issue and I should be able to add support for these files without too much work.

* UF writing in Py-ART relatively slow, probably no good way around this without some serious optimization.

**Comment by gamaanderson** [comment]
BUG: in [line 265](https://github.com/ARM-DOE/pyart/blob/master/pyart/io/uf_write.py#L265) it should be ` / 1000` and not ` * 1000`, this is causing overflow and consequent error while packing. Also in line 266 I believe `'range_start_m'` is just the decimal part of the range, otherwise a start range of `33 km` will overflow and I don't see a reason for repeating the information. Sorry it took so long for reporting this bug.

Also I would have found more comfortable, fields not present in `uf_field_names` to be excluded from writing, and not causing an KeyError: in [line 150](https://github.com/ARM-DOE/pyart/blob/master/pyart/io/uf_write.py#L265). But you probably have your reasons for not doing so.

**Comment by jjhelmus** [comment]
Thanks @gamaanderson for catching these.  All three of these are bugs, I will have a fix for them shortly.

**Comment by jjhelmus** [comment]
PR #400 fixes all three of these bugs.
