### ISSUE TITLE
"unknown compression record" for some NEXRAD files

### ISSUE THREAD

**Issue by jzbontar** [ARM-DOE/pyart#552]
Hi,

I'm getting "unknown compression record" errors when reading some NEXRAD level 2 archive files, for example [KDIX19960521_185016.gz](https://noaa-nexrad-level2.s3.amazonaws.com/1996/05/21/KDIX/KDIX19960521_185016.gz). Here is the code to reproduce the bug:

    import pyart
    radar = pyart.io.read('KDIX19960521_185016.gz')

I have traced the problem down to the elif statement in [io/nexrad_level2.py](https://github.com/ARM-DOE/pyart/blob/master/pyart/io/nexrad_level2.py#L141). The compression record for some NEXRAD level 2 files is `b'\t\x80'` instead of `b'\x00\x00'`. Other than the unexpected compression record entry, KDIX19960521_185016.gz seems to be a valid radar scan. A solution that worked for me was to replace the elif statement in [io/nexrad_level2.py](https://github.com/ARM-DOE/pyart/blob/master/pyart/io/nexrad_level2.py#L141) with the following:

    elif compression_record[compression_slice] in {b'\x00\x00', b'\t\x80'}:

**Comment by jjhelmus** [comment]
@jzbontar Thanks for reporting this.  From some research I've done it looks like the 12-byte `compression_header` that Py-ART reads from NEXRAD level 2 files used to hold the Channel Terminal Manager (CTM).  This is typically zeroed out in newer NEXRAD files but older files may still contain CTM data.  You fix is exactly what we need, I'll


Why `b'\t\x80'`?
Some digging suggests that the CTM contains six big-endian unsigned shorts, the third of which, bytes 4:6, contains the record size.  In the nexrad_level2.py module these bytes are referred to as the `compression_record`.  Since NEXRAD records are 2432 bytes long the value of this record should be `struct.pack('>H', 2432)` which is `b'\t\x80'`.
