### ISSUE TITLE
ARM Radar Group link broken

### ISSUE THREAD

**Issue by zssherman** [ARM-DOE/pyart#725]
The ARM Radar Group link found on the page here http://arm-doe.github.io/pyart is broken. @scollis Want it removed or replaced with something different? The link embedded http://radar.arm.gov/ARM_Radars/ doesn't exist, and removing the /ARM_Radars the link  http://radar.arm.gov/ then redirects to WARNOs page.

**Comment by zssherman** [comment]
And it seems the GitHub Repo and source code both are the same links, so if you want me to remove one of them?

**Comment by scollis** [comment]
A good docfix is always welcome!


Scott Collis


On Apr 4, 2018 at 11:03 AM, Zach Sherman <notifications@github.com> wrote:


And it seems the GitHub Repo and source code both are the same links, so if
you want me to remove one of them?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ARM-DOE/pyart/issues/725#issuecomment-378673120>, or mute
the thread

**Comment by zssherman** [comment]
Fix in #728 closing.
