### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by Ahmed042018** [ARM-DOE/pyart#771]
Hi everyone,
 Can any one please help me to fix this, I used StanfordParser to pars a text and need to remove this warning from the outputs. 

DeprecationWarning: The StanfordParser will be deprecated Please use nltk.parse.corenlp.StanforCoreNLPParser instead.

**Comment by scollis** [comment]
Please do not use the issue tracker to ask question.

Email this to pyart-users@googlegroups.com

Scott Collis


On Oct 1, 2018 at 1:10 PM, Ahmed042018 <notifications@github.com> wrote:


Hi everyone,
Can any one please help me to fix this, I used StanfordParser to pars a
text and need to remove this warning from the outputs.

DeprecationWarning: The StanfordParser will be deprecated Please use
nltk.parse.corenlp.StanforCoreNLPParser instead.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ARM-DOE/pyart/issues/771>, or mute the thread
